version: "2"
services: 
    apache-server:
        image: httpd:2.4
        expose:
           - 80
           - 443
        ##################注意：端口为9090 可更改为 80######################
        ports:
           - 80:80
           - 443:443
        volumes:
           - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
           - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
           - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/apache/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
           #- /home/qiang/vboxshare/server_log/nginx_log:/var/log/nginx
        volumes_from:
           - data-web-www
        links:
           - phpfpm-server-7.0.30:phpfpm-server-70
    phpfpm-server-7.0.30:
        image: zhiqiangvip/docker-php-7.0.30-fpm
        expose: 
           - 9000
        #   - 9566
        #ports:
        #   - 9566:9566
        ##################PHP-FPM 配置文件######################
        volumes: 
           - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/php7.0.30-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
           - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/php7.0.30-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
           - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/php7.0.30-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
        volumes_from:
           - data-web-www
        links:
           - mysql-server-5.6:mysql-server-5.6
           - redis-server:redis-server
    mysql-server-5.6:
            image: zhiqiangvip/docker-mysql5.6
            expose:
               - 3306
            ports:
               - 3306:3306
            environment:
               - MYSQL_PASS=DAqvfG2FDUaVd5wv
            #################配置数据库文件挂载目录######################
            volumes:
               - /home/ubuntu/app/docker_server_data/mysql56_db:/data
               - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/mysql56/extend.cnf:/etc/mysql/conf.d/extend.cnf
               - /home/ubuntu/app/docker_server_data/mysql_log:/var/log/mysql
    redis-server:
            image: redis:3-alpine
            volumes:
               - /home/ubuntu/app/docker_server_data/redis_db:/data
               - /home/ubuntu/app/docker_server/DOCKER_SERVER_CONF/redis3.2/redis.conf:/usr/local/etc/redis/redis.conf
            command: redis-server /usr/local/etc/redis/redis.conf
            expose:
               - 6379
            ports:
               - 6377:6379

    data-web-www:
        image: alpine
        ###################配置网站www目录挂载目录######################
        volumes: 
           - /home/ubuntu/app/docker_server_data/web_www:/data
